// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CustomData custom data object
//
// swagger:model CustomData
type CustomData struct {

	// Full sha of commit
	// Required: true
	CommitSha *string `json:"commit_sha"`

	// data
	// Required: true
	Data JSONObject `json:"data"`

	// Full repo name "github.com/Clever/<name>"
	// Required: true
	RepoName *string `json:"repo_name"`
}

// Validate validates this custom data
func (m *CustomData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommitSha(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRepoName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CustomData) validateCommitSha(formats strfmt.Registry) error {

	if err := validate.Required("commit_sha", "body", m.CommitSha); err != nil {
		return err
	}

	return nil
}

func (m *CustomData) validateData(formats strfmt.Registry) error {

	if err := m.Data.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("data")
		}
		return err
	}

	return nil
}

func (m *CustomData) validateRepoName(formats strfmt.Registry) error {

	if err := validate.Required("repo_name", "body", m.RepoName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CustomData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomData) UnmarshalBinary(b []byte) error {
	var res CustomData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
