routes:
  parse-error:
    matchers:
      title: ["parse-error"]
    output:
      type: "notifications"
      channel: "#breakdown-alerts"
      icon: ":rock-sus:"
      message: "error parsing file `%{path}` from `%{repo}@%{sha}`: `%{message}`"
      user: "Dwayne 'The Rock' Johnson"
