swagger: '2.0'
info:
  title: breakdown
  description: breaks down packages within repos
  # when changing the version here, make sure to run
  # `make generate` to generate clients and server
  version: 0.1.0
  x-npm-package: '@clever/breakdown'
schemes:
  - http
produces:
  - application/json
responses:
  BadRequest:
    description: "Bad Request"
    schema:
      $ref: "#/definitions/BadRequest"
  InternalError:
    description: "Internal Error"
    schema:
      $ref: "#/definitions/InternalError"
  NotFound:
    description: Entity Not Found
    schema:
      $ref: "#/definitions/NotFound"
paths:
  /_health:
    get:
      operationId: healthCheck
      description: Checks if the service is healthy
      responses:
        200:
          description: OK response

  /v2/things:
    get:
      summary: List things
      operationId: getThings
      parameters: []
      responses:
        200:
          description: Array of things.
          schema:
            type: array
            items:
              $ref: "#/definitions/Thing"

  /v2/things/{id}:
    put:
      summary: Creates or updates a thing.
      operationId: createOrUpdateThing
      parameters:
        - name: thing
          in: body
          schema:
            $ref: "#/definitions/Thing"
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: The created or updated thing.
          schema:
            $ref: "#/definitions/Thing"
        400:
          description: Bad request.
          schema:
            $ref: "#/definitions/BadRequest"
    get:
      summary: Get a thing by id.
      operationId: getThing
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        200:
          description: The thing object.
          schema:
            $ref: "#/definitions/Thing"
        404:
          $ref: "#/responses/NotFound"
    delete:
      summary: Delete a thing.
      operationId: deleteThing
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        200:
          description: OK
        404:
          $ref: "#/responses/NotFound"

definitions:
  Thing:
    description: provided as an example
    type: object
    properties:
      id:
        type: string
      foo:
        type: string

  ErrorCode:
    type: string
    enum:
      - InvalidID
      # place more error codes that clients can identify and act upon

  InternalError:
    type: object
    properties:
      message:
        type: string
      code:
        $ref: "#/definitions/ErrorCode"

  BadRequest:
    type: object
    properties:
      message:
        type: string
      code:
        $ref: "#/definitions/ErrorCode"

  NotFound:
    type: object
    properties:
      message:
        type: string
      code:
        $ref: "#/definitions/ErrorCode"
